" Turn off compatibility mode
set nocp
" set encoding (required by ycm)
set encoding=utf-8
" allow backspacing over everything in insert mode
set backspace=indent,eol,start
" allow unwritten buffers
set hidden
" keep 1000 lines of command line history
set history=1000
" use more levels of undo
set undolevels=1000
" disable swap file
set noswapfile
" line numbers
set number
" show the cursor position all the time
set ruler
" display incomplete commands
set showcmd
" do incremental searching
set incsearch
" wrap lines on 'word' boundaries
set linebreak
" don't let the cursor touch the edge of the viewport
set scrolloff=3
" Vertical splits use right half of screen
set splitright
set timeout
" Lower ^[ timeout
set timeoutlen=1000
" get rid of obnoxious '-' characters in folds
set fillchars=fold:\ ,
" disable source code folding
set foldlevelstart=99
" use ~ to toggle case as an operator, not a motion
set tildeop
" new at bottom
set splitbelow
" show options above commandline
set wildmenu
" show whitespace characters
set listchars=eol:$,trail:·,tab:»·
" configure wildmenu to ignore some not wanted files
set wildignore+=*.o,*.d,*.elf
" use normal clipboard shared with Ctrl-C/Shift-Ins
set clipboard=unnamedplus
" enable project specific vimrc
set exrc
if exists('&breakindent')
  set breakindent      " Indent wrapped lines up to the same level
endif

" Tabulator settings
set expandtab          " Expand tabs into spaces
set tabstop=4          " default spaces for a hard tab
set softtabstop=4      " default spaces for the soft tab
set shiftwidth=4       " for when <TAB> is pressed at the beginning of a line

" completer options
"set completeopt=longest,menuone

" use ripgrep for searching
if executable('rg')
    set grepprg=rg\ --vimgrep\ --no-heading
endif

" Mouse settings
if has('mouse')
  set mouse=a          " if mouse is available make use of it
endif

" look for plugins in home dir
set runtimepath+=~/.local/share/vim/addons/*/
set runtimepath+=~/.local/share/fzf

" enable syntax
syntax enable
filetype plugin indent on
filetype plugin on

" prevent cwindow and location be opened in normal buffers when switching
autocmd BufWinEnter quickfix setlocal nobuflisted
autocmd BufWinEnter location setlocal nobuflisted

" Apperance/color scheme settings
if match($TERM, "xterm")!=-1
    set term=xterm-256color
endif

" load generic configurations
runtime! vimrc-airline
runtime! vimrc-filetypes
runtime! vimrc-gitgutter
runtime! vimrc-map
runtime! vimrc-nerdcommenter
runtime! vimrc-nerdtree
runtime! vimrc-syntastic
runtime! vimrc-theme

if &diff
    runtime! vimrc-diff
else
    runtime! vimrc-ide
    runtime! vimrc-ycm
endif

" Enable security for project specific vimrc
set secure
